import sys

from timeit import default_timer as timer
from datetime import timedelta


print('------------------------------------')
print('   Generate the 2 characters passcode   ')
print('------------------------------------')

# below are 3 lists - a-z, A-Z, 0-9

charlist_l = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u',
              'v', 'w', 'x', 'y', 'z', ]

charlist_u = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U',
              'V', 'W', 'X', 'Y', 'Z', ]

charlist_n = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

characters = []

name = input('player, what is your name? ')

def get_code():
    global code
    code = input(name + ", what is your secret 2 character code...shhhhh I won't tell? ")
    global left
    left = code[0]
    global right
    right = code[1]
get_code()
# you could comment out some of the below appends to make the initial list simpler
for i in range(len(charlist_l)):
    characters.append(charlist_l[i])
for i in range(len(charlist_u)):
    characters.append(charlist_u[i])
for i in range(len(charlist_n)):
    characters.append(charlist_n[i])

found = False

start = timer()

if left not in characters:
    print("Your item will not be able to be generated. You have used a character I do not know")
    end = timer()
    time_taken = timedelta(seconds=end - start)
    print("It took about ", time_taken, 'to find your passcode could not be generated by my list')
    print("")
    print("I have now added your character to my list as I can learn a new character")
    characters.append(left)
    get_code()

if right not in characters:
    print("Your item will not be able to be generated. You have used a character I do not know")
    end = timer()
    time_taken = timedelta(seconds=end - start)
    print("It took about ", time_taken, 'to find your passcode could not be generated by my list')
    print("")
    print("I have now added your character to my list as I can learn a new character")
    characters.append(right)
    get_code()

else:
    start = timer()
    for a in range(len(characters)):
        position_1 = characters.index(left)
        for b in range(len(characters)):
            position_2 = characters.index(right)
            if characters[a] + characters[b] == code:
                found = True
                end = timer()
                time_taken = timedelta(seconds=end - start)
                print('')
                print(found, "... the code can be created by my list")
                print("at locations ", position_1,",", position_2, " in the list")
                print("It took about ", time_taken, 'milliseconds to generate your passcode',characters[a] + characters[b])
if found:
    sys.exit()



